name: Frontend Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy frontend to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "=== Updating code ==="
            cd /home/ec2-user/Frontend
            git pull origin main

            echo "=== Building new Docker image ==="
            docker build --no-cache -t react_frontend .

            echo "=== Restarting container ==="
            docker stop react_frontend || true
            docker rm react_frontend || true
            docker run -d -p 80:80 --name react_frontend react_frontend
